apiVersion: apps/v1
kind: Deployment
metadata:
  name: openwebui
  namespace: ollama-system
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openwebui
  template:
    metadata:
      labels:
        app: openwebui
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "3000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
      - name: openwebui
        image: azurecr.io/ollamawebui/openwebui:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: OLLAMA_BASE_URL
          value: "http://ollama.ollama-system.svc.cluster.local:11434"
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: openwebui
  namespace: ollama-system
spec:
  selector:
    app: openwebui
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP