apiVersion: v1
kind: Namespace
metadata:
  name: ollama-system
  labels:
    name: ollama-system
    environment: production
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring