version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: azure-ollama-prod
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      - ./models:/models
    environment:
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: unless-stopped

  openwebui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: azure-openwebui-prod
    ports:
      - "3000:3000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
      - NODE_ENV=production
    depends_on:
      - ollama
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
    restart: unless-stopped

volumes:
  ollama_data: